Add api.key auth fallback and project_path
logicalclocks/machine-learning-api pull request #100
Opened 2022-05-18 11:40 UTC by javierdlrm

2022-05-19 12:43 UTC, robzor92 requested changes

2022-05-19 12:43 UTC, robzor92 commented on python/hsml/engine/serving_engine.py
> +            print(
Maybe should be an exception instead?

2022-05-20 13:01 UTC, javierdlrm commented on python/hsml/engine/serving_engine.py
> +            print(
I agree

2022-05-20 13:13 UTC, robzor92 approved these changes

2022-05-23 07:06 UTC, merged