[HWORKS-352] Make input example consistent across data types
logicalclocks/machine-learning-api pull request #171
Opened 2023-01-03 12:08 UTC by javierdlrm

2023-01-31 11:03 UTC, robzor92 requested changes

2023-01-31 11:03 UTC, robzor92 commented on python/hsml/model.py
> +            `Model`. The deployment metadata object.
```suggestion
            `Model`. The model metadata object.
```

2023-02-03 08:37 UTC, javierdlrm commented on docs/index.md
> +# Hopsworks Model Management
Not sure now. Maybe it was part of a cherry-picked commit.
I'll remove it, since I don't see where it is used

2023-02-03 09:18 UTC, javierdlrm commented on python/hsml/engine/serving_engine.py
> +    def _build_inference_payload(self, data, inputs):
Done

2023-02-03 14:16 UTC, robzor92 approved these changes

2023-02-14 09:11 UTC, merged