[FSTORE-1346] Upgrade doc dependencies, contributing.md, mkdocs workflows
logicalclocks/machine-learning-api pull request #221
Opened 2024-04-09 10:51 UTC by vatj

2024-04-15 11:36 UTC, robzor92 requested changes

2024-04-15 11:36 UTC, robzor92 commented on CONTRIBUTING.md
> -4. For this you can either checkout and make a local copy of the `upstream/gh-pages` branch, where
The section below here does not render correctly

2024-04-15 11:36 UTC, robzor92 commented on docs/CONTRIBUTING.md
> -4. For this you can either checkout and make a local copy of the `upstream/gh-pages` branch, where
The section below here does not render correctly

2024-04-15 11:37 UTC, robzor92 requested changes
mkdocs-release workflow doesn't work and should we not also add this change? https://github.com/logicalclocks/feature-store-api/pull/1275/files

2024-04-17 06:03 UTC, vatj commented
Added the changes, still testing it

2024-04-29 13:42 UTC, vatj commented
Merged into FSTORE-1371

2024-04-29 13:42 UTC, closed without merging