[HWORKS-936][APPEND] explicit provenance - model
logicalclocks/machine-learning-api pull request #235
Opened 2024-05-07 08:14 UTC by o-alex

2024-05-08 10:34 UTC, o-alex commented
Should only be merged after https://github.com/logicalclocks/machine-learning-api/pull/235

2024-05-10 13:59 UTC, bubriks requested changes

2024-05-10 13:59 UTC, bubriks commented on python/hsml/model.py
>          return fv
```suggestion
        return explicit_provenance.Links.get_one_accessible_parent(fv_prov)
```

2024-05-10 13:59 UTC, bubriks commented on python/hsml/core/explicit_provenance.py
> +    def get_one_accessible_parent(links):
maybe we could use some basic tests for this method.

2024-05-13 10:16 UTC, bubriks approved these changes

2024-05-13 10:50 UTC, merged